services:
  postgres:
    image: postgres:16
    container_name: uniflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uniflow
      POSTGRES_PASSWORD: uniflow_dev
      POSTGRES_DB: uniflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: